apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: redhat-gear
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: quay.io/redhat-ads-tech/redhat-gear-inventory-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_VALIDATOR_URL
              value: "http://payment-validator.payment-services.svc.cluster.local:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
