apiVersion: v1
kind: Service
metadata:
  name: payment-validator
  namespace: payment-services
  labels:
    app: payment-validator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payment-validator
